[general]
# import
working_directory="C:\\code-win"
live_config_reload=true
# ipc_socket

[window]
# dimensions
position="None"

# padding
dynamic_padding=false

decorations="Full"
opacity=0.7
blur=false

startup_mode="Fullscreen"

title="Alacritty"
dynamic_title=true
# class

decorations_theme_variant="None"
resize_increments=false
option_as_alt="None"

level="Normal"

[scrolling]
history=100000
multiplier=3

[font]
normal={ family="MesloLGM Nerd Font", style="Regular" }
bold={ style = "Bold" }
italic={ style = "Italic" }
bold_italic={ style = "Bold Italic" }
size=11.00
offset={ x = 0, y = 0 }
# glyph_offset
builtin_box_drawing=true

[colors]

cursor={ text = "CellBackground", cursor = "CellForeground" }

[colors.primary]
foreground="#d8d8d8"
background="#181818"
dim_foreground="#828482"
bright_foreground="None"

# [...]

[selection]
semantic_escape_chars=",â”‚`|:\"' ()[]{}<>\t"
save_to_clipboard=true

[terminal]
shell="powershell"
soc52="OnlyCopy"
