# ---------------------------------------------------------------------------- #
#               ------- Ruff Default Configuration ------
# ---------------------------------------------------------------------------- #
# https://docs.astral.sh/ruff

# Number of spaces per indentation level
indent-width = 4
line-length = 160
# Whether to automatically exclude files that are ignored by .gitignore
respect-gitignore = true
target-version = "py311"

[format]
# https://docs.astral.sh/ruff/formatter
# Like Black, use double quotes over single quotes for strings
quote-style = "double"
# Like Black, indent with spaces, rather than tabs
indent-style = "space"
# Like Black, automatically detect the correct line ending.
line-ending = "auto"

# Enable reformatting of code snippets in docstrings
docstring-code-format = true
# Ignore trailing commas used as an indication that short lines should be left separate
skip-magic-trailing-comma = true

[lint]
# https://docs.astral.sh/ruff/linter
select = [
    "ERA",  # eradicate
    "S",    # flake8-bandit
    "B",    # flake8-bugbear
    "A",    # flake8-builtins
    "COM",  # flake8-commas
    "C4",   # flake8-comprehensions
    "DTZ",  # flake8-datetimez
    "ISC",  # flake8-implicit-str-concat
    "ICN",  # flake8-import-conventions
    "G",    # flake8-logging-format
    "Q",    # flake8-quotes
    "RSE",  # flake8-raise
    "RET",  # flake8-return
    "SLF",  # flake8-self
    "SIM",  # flake8-simplify
    "TID",  # flake8-tidy-imports
    "ARG",  # flake8-unused-arguments
    "PTH",  # flake8-use-pathlib
    "I",    # isort
    "PD",   # pandas-vet
    "N",    # pep8-naming
    "PERF", # perflint
    "E",    # pycodestyle
    "D",    # pydocstyle
    "F",    # Pyflakes
    "PL",   # Pylint
    "UP",   # pyupgrade
    "FURB", # refurb
    "RUF",  # Ruff-specific rules
]

# Lint rules in conflict with the formatter: COM812, COM819, D206, D300, E111, E114, E117, Q000, Q001, Q002, Q003
ignore = [
    "COM812", # missing-trailing-comma
    "COM819", # prohibited-trailing-comma
    "D206",   # docstring-tab-indentation
    "D300",   # triple-single-quotes
    "E111",   # indentation-with-invalid-multiple
    "E114",   # indentation-with-invalid-multiple-comment
    "E117",   # over-indented
    "Q000",   # bad-quotes-inline-string
    "Q001",   # bad-quotes-multiline-string
    "Q002",   # bad-quotes-docstring
    "Q003",   # avoidable-escaped-quote
    # ------#
    "D203",    # incorrect-blank-line-before-class
    "D213",    # multi-line-summary-second-line
    "PLR0913", # too-many-arguments
    "PLW0603", # global-statement
]

[lint.isort]
# https://docs.astral.sh/ruff/settings/#lintisort
case-sensitive = true
split-on-trailing-comma = false

[lint.pydocstyle]
# https://docs.astral.sh/ruff/settings/#lintpydocstyle

# Whether to use Google-style, NumPy-style conventions, or the PEP 257 defaults when analyzing docstring sections
convention = "google"
# Ignore missing documentation for *args and **kwargs parameters.
ignore-var-parameters = true
